<a href="https://colab.research.google.com/github/Niraj7667/ML-models/blob/main/outliers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd

df = pd.read_csv("AB_NYC_2019.csv")
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [14]:
max_threshold = (df['price']/df['minimum_nights']).quantile(0.99)
max_threshold

np.float64(443.0)

In [15]:
df2 = df[(df['price']/df['minimum_nights'])>max_threshold]

In [16]:
min_threshold = (df['price']/df['minimum_nights']).quantile(0.01)
min_threshold

np.float64(1.2333333333333334)

In [17]:
min_threshold_df = df[(df['price']/df['minimum_nights'])<min_threshold]
min_threshold_df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
36,11452,Clean and Quiet in Brooklyn,7355,Vt,Brooklyn,Bedford-Stuyvesant,40.68876,-73.94312,Private room,35,60,0,NaN,NaN,1,365
245,61509,"Quiet, clean midtown apt w. elevato",23619,Anna/Fonzy,Manhattan,Midtown,40.75749,-73.96897,Entire home/apt,110,200,92,2019-04-30,0.90,1,140
349,94209,LARGE 1BR (CONV 2BR) CROWN HEIGHTS,503800,Sadatu,Brooklyn,Crown Heights,40.67473,-73.94494,Entire home/apt,100,90,0,NaN,NaN,1,365
441,152520,Female Only Clean15min to Manhattan,733894,Lucy,Queens,Sunnyside,40.73850,-73.91806,Private room,42,40,53,2018-11-16,0.55,3,236
457,161366,Sunny 15min to Manhattan LADY only,733894,Lucy,Queens,Sunnyside,40.74102,-73.91681,Private room,42,40,41,2019-06-01,0.43,3,246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48636,36351543,2-MONTH SUBLEASE (WITH EARLY MOVE-IN),52984497,Friday,Brooklyn,Bedford-Stuyvesant,40.68914,-73.92408,Private room,33,30,2,2019-07-06,2.00,1,87
48753,36418759,"Spacious Room w/ AC, Laundry, WiFi + Free Clea...",154980356,Joanne & Robert,Brooklyn,Bedford-Stuyvesant,40.68600,-73.93000,Private room,32,30,0,NaN,NaN,1,10
48772,36424129,Bright & Cheerful! Modern w/ Laundry + Fast WiFi,107407045,Brett & Megan,Brooklyn,Bedford-Stuyvesant,40.69217,-73.93191,Private room,35,30,0,NaN,NaN,1,44
48774,36424334,Laundry + Central AC - Modern Style - Near Metro,155298656,Brad & Rachel,Queens,Ridgewood,40.70585,-73.91298,Private room,35,30,0,NaN,NaN,1,44
48871,36475746,A LARGE ROOM - 1 MONTH MINIMUM - WASHER&DRYER,144008701,Ozzy Ciao,Manhattan,Harlem,40.82233,-73.94687,Private room,35,29,0,NaN,NaN,2,31

In [18]:
df3 = df[((df['price']/df['minimum_nights'])>min_threshold)  & ((df['price']/df['minimum_nights']) < max_threshold)]

In [20]:
df3.shape

(47898, 16)